- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: copy expense config file
  ansible.builtin.copy:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: start nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes
- name: App prerequisites
  ansible.builtin.import_role:
    name: common
    tasks-from: app-prereq
  vars:
    app_dir: /usr/share/nginx/html
    component: frontend
